### ISSUE TITLE
通过WiFi连接手机和车机，在车机APP测试下一曲按钮

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#20]
### Bug Report
通过WiFi连接手机和车机，在车机APP测试下一曲按钮

##### Reproduction Steps

1 | 正常启动QTHMI程序，并点击Application
2 | 在手机上启动SDL Example APP，输入SDL的IP地址，并点击Connect
3 | 在车机端启动APP
4 | 点击下一曲按钮

##### Expected Behavior
车机正常启动并显示Application界面：YES
车机显示SDL Example应用: YES
车机端进入SDL Example界面: YES
手机端进入锁屏界面: YES
车机端播放下一曲：YES

##### Observed Behavior
车机端没有音乐播放，也没有切换至下一曲

##### OS & Version Information
* OS/Version: iOS 11.4
* SDL Core Version: [The version of SDL Core you were using when the bug occurred]
* SDL Proxy Version：[The version of SDL Android/ SDL iOS you were using when the bug occurred]
* Testing Against: [What you tested with to observe this behavior. Proxy, App, HMI etc.]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by zenghuan1** [comment]
测试app无音乐可切换,点击下一曲之后,log中有上发切换下一曲的消息,但是无切换到下一曲的消息发送回来.
目前分析为测试app无消息返回的问题.
