### ISSUE TITLE
Incoming phone call, Call is ended by SYNC

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#23]
### Bug Report

Incoming phone call, Call is ended by SYNC

##### Reproduction Steps

1 | Use another phone to place a call to the iPhone connected to SYNC.
2 | Accept incoming call by pressing the "Accept" button on the sync screen.
3 | Terminate the call by pressing the "End Call" button on the sync screen.

##### Expected Behavior

A call is placed to the test iPhone
App Audio: paused. (Media Apps Only)
HMI: Background/Not_Audible
Phone Call: In progress
App Audio: Resume (Media Apps Only)App Base screen is displayed on Sync: YES
HMI: FULL/Audible
Lockscreen on Phone: YES
Phone Call: Ended

##### Observed Behavior

手机打入电话，车机没有显示通话，并且无法切断通话。

##### OS & Version Information
* OS/Version:iOS 11.4
* SDL Core Version: [The version of SDL Core you were using when the bug occurred]
* SDL Proxy Version：[The version of SDL Android/ SDL iOS you were using when the bug occurred]
* Testing Against: [What you tested with to observe this behavior. Proxy, App, HMI etc.]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by zenghuan1** [comment]
当前HMI 无手机通话相关的实际功能,不支持通过HMI去操作手机的通话.
