### ISSUE TITLE
Incoming phone call, User rejects call

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#24]
### Bug Report

Incoming phone call, User rejects call

##### Reproduction Steps

1 | Lock the iPhone by pressing the button on top of the device.
2 | Use another phone to place a call to the iPhone connected to SYNC.
3 | User rejects incoming call by pressing the "Reject" button on the SYNC screen.

##### Expected Behavior

Phone Locked: YES
Black Screen on Phone: YES
App Audio: paused. (Media Apps Only)
HMI: Background/Not_Audible
Phone Call: Ringing
App Audio: Resume (Media Apps Only) App Base screen is displayed on Sync: YES
HMI: FULL/Audible
Lockscreen when app in focus: YES

##### Observed Behavior
用户手机来电，音频没有暂停

##### OS & Version Information
* OS/Version:iOS 11.4
* SDL Core Version: [The version of SDL Core you were using when the bug occurred]
* SDL Proxy Version：[The version of SDL Android/ SDL iOS you were using when the bug occurred]
* Testing Against: [What you tested with to observe this behavior. Proxy, App, HMI etc.]

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by zenghuan1** [comment]
当前QtHMI不支持语音通话功能 ,请关闭.
