### ISSUE TITLE
通过WiFi连接手机和车机，在车机端测试Show

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#26]
### Bug Report

通过WiFi连接手机和车机，在车机端测试Show

##### Reproduction Steps

1 | 正常启动QTHMI程序，并点击Application
2 | 在手机上启动SPT3，在左侧菜单栏选择Current APP settings，在protocol处选择TCP/IP Specification,并输入车机的IP地址和Port，并点击右上角的Save
3 | 在手机端Alert弹窗中选择YES
4 | 在车机端启动APP
5 | 在手机端点击SEND MESSAGE按钮
6 | 在手机端点击Show按钮
7 | 在手机端点击底部Send RPC按钮

##### Expected Behavior

车机正常启动并显示Application界面：YES
手机端弹出Alert弹窗，并显示警告信息：YES
车机显示SyncProxyTester应用: YES
车机端进入SyncProxyTester界面: YES
手机端显示RPCs列表：YES
手机端显示Show界面：YES
车机端右侧显示One和Two
车机端显示在手机端设置的所有的line：YES

##### Observed Behavior

手机端设置了4行内容，车机端只显示了三行

##### OS & Version Information
* OS/Version: iOS 11.4
* SDL Core Version: [The version of SDL Core you were using when the bug occurred]
* SDL Proxy Version：[The version of SDL Android/ SDL iOS you were using when the bug occurred]
* Testing Against: [What you tested with to observe this behavior. Proxy, App, HMI etc.]

##### Test Case, Sample Code, and / or Example App
APPName：SPT3

**Comment by zenghuan1** [comment]
当前使用的是media 模板,中间的音乐信息显示只支持3行显示.请关闭.
