### ISSUE TITLE
车机端通过蓝牙连接最美天气APP，车机端测试城市列表显示

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#33]
### Bug Report
车机端通过蓝牙连接最美天气APP，车机端测试城市列表显示

##### Reproduction Steps
1 | 正常启动QTHMI程序，并点击Application
2 | 手机和车机蓝牙配对，在手机端启动最美天气App
3 | 在车机端启动最美天气APP
4 | 在车机端点击选择城市按钮
##### Expected Behavior

车机正常启动并显示Application界面：YES
车机显示最美天气应用: YES
车机端进入最美天气界面: YES
车机端进入选择城市界面：YES
车机端显示选择城市列表：YES

##### Observed Behavior
车机端无法显示城市列表

##### OS & Version Information
* OS/Version:Android 6.0.1
* SDL Core Version: 4.4.1
* SDL Proxy Version： branch master(commit 48fe3a9810e30b78eca7ce63bd13ff03d496932f)
##### Test Case, Sample Code, and / or Example App
最美天气

**Comment by zenghuan1** [comment]
当前环境不支持GPS,所以无城市列表显示显示.
