### ISSUE TITLE
通过蓝牙连接车机和最美天气App，车机端点击预警信息按钮			

### ISSUE THREAD

**Issue by lpz191** [APCVSRepo/HMI_SDK_LIB#34]
### Bug Report
通过蓝牙连接车机和最美天气App，车机端点击预警信息按钮			

##### Reproduction Steps

1 | 正常启动QTHMI程序，并点击Application
2 | 手机和车机蓝牙配对，在手机端启动最美天气App
3 | 在车机端启动最美天气APP
4 | 在车机端点击预警信息按钮

##### Expected Behavior

车机正常启动并显示Application界面：YES
车机显示最美天气应用: YES
车机端进入最美天气界面: YES
车机端进入预警信息界面：YES
车机端显示预警信息：YES 

##### Observed Behavior

进入预警信息界面，但是未显示任何内容

##### OS & Version Information
* OS/Version:Android 6.0.1
* SDL Core Version: 4.4.1
* SDL Proxy Version：branch master(commit 48fe3a9810e30b78eca7ce63bd13ff03d496932f)

##### Test Case, Sample Code, and / or Example App
最美天气 V4.02

**Comment by zenghuan1** [comment]
当前环境无GPS天线支持,所以无预警信息显示.
