### ISSUE TITLE
蓝牙连接最美天气App，车机端点击返回按钮

### ISSUE THREAD

**Issue by EggeWang** [APCVSRepo/HMI_SDK_LIB#35]
### Bug Report
蓝牙连接最美天气App，车机端点击返回按钮

##### Reproduction Steps
1 | 正常启动QTHMI程序，并点击Application
2 | 手机和车机蓝牙配对，在手机端启动最美天气App
3 | 在车机端启动最美天气APP
4 | 在车机端点击返回按钮

##### Expected Behavior
车机正常启动并显示Application界面：YES
车机显示最美天气应用: YES
车机端进入最美天气界面: YES
车机端返回Application列表界面并显示App列表：YES

##### Observed Behavior
车机端点击返回按钮后，界面无任何变化

##### OS & Version Information
OS & Version Information
OS/Version:Android 6.0.1
SDL Core Version: 4.4.1
SDL Proxy Version：branch master(commit 48fe3a9)

##### Test Case, Sample Code, and / or Example App
最美天气 V4.02

**Comment by zenghuan1** [comment]
模板不支持当前画面按钮返回,已修正,请关闭.

**Comment by zenghuan1** [comment]
模板不支持当前画面按钮返回,已修正,请关闭.
