### ISSUE TITLE
车机端点击上一曲或下一曲的时候播放按钮未切换

### ISSUE THREAD

**Issue by zhuangzhuangyong** [APCVSRepo/HMI_SDK_LIB#37]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
[Summary]
车机端点击上一曲或下一曲的时候播放按钮未切换
##### Reproduction Steps
1. [Step 1]
正常启动QTHMI程序，并点击Application
2. [Step 2]
手机和车机蓝牙配对，在手机端启动QQ音乐App
3. [Step 3]
在车机端启动QQ音乐APP
4. [Step 4]
车机端暂停播放音乐
5. [Step 5]
车机端点击下一曲或者上一曲

##### Expected Behavior
[Some expected behavior]
车机端播放音乐并切换成播放按钮状态
##### Observed Behavior
[Some observed behavior]
车机端播放音乐但是并未切换成播放按钮状态

##### OS & Version Information
OS/Version:Android 6.0.1
SDL Core Version: 4.4.1
SDL Proxy Version： branch master(commit 48fe3a9)
Test Case, Sample Code, and / or Example App

QQ音乐

**Comment by zenghuan1** [comment]
点击上一曲发送后,收到"updateMode" : "COUNTUP" 消息,再收到"updateMode" : "PAUSE"
消息导致问题.分析原因为QQ音乐消息时序导致问题.
